/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni_202457201057;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author HP
 */
public class f_dasboard extends javax.swing.JFrame {

    /**
     * Creates new form f_dasboard
     */
    public f_dasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_Panel = new javax.swing.JPanel();
        sideBar_Panel = new javax.swing.JPanel();
        b_dasboard = new javax.swing.JButton();
        b_jurusan = new javax.swing.JButton();
        b_guru = new javax.swing.JButton();
        b_kelas = new javax.swing.JButton();
        b_siswa = new javax.swing.JButton();
        b_about = new javax.swing.JButton();
        b_logout = new javax.swing.JButton();
        content_Panel = new javax.swing.JPanel();
        bClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        main_Panel.setPreferredSize(new java.awt.Dimension(1290, 768));

        sideBar_Panel.setBackground(new java.awt.Color(204, 102, 255));

        b_dasboard.setBackground(new java.awt.Color(204, 102, 255));
        b_dasboard.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        b_dasboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Dashboard Gauge2.png"))); // NOI18N
        b_dasboard.setText("Dashboard");
        b_dasboard.setBorder(null);
        b_dasboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b_dasboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dasboardActionPerformed(evt);
            }
        });

        b_jurusan.setBackground(new java.awt.Color(204, 102, 255));
        b_jurusan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        b_jurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/School Building.png"))); // NOI18N
        b_jurusan.setText("Jurusan");
        b_jurusan.setBorder(null);
        b_jurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_jurusanActionPerformed(evt);
            }
        });

        b_guru.setBackground(new java.awt.Color(204, 102, 255));
        b_guru.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        b_guru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Classroom.png"))); // NOI18N
        b_guru.setText("Guru");
        b_guru.setBorder(null);
        b_guru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guruActionPerformed(evt);
            }
        });

        b_kelas.setBackground(new java.awt.Color(204, 102, 255));
        b_kelas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        b_kelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Class2.png"))); // NOI18N
        b_kelas.setText("Kelas");
        b_kelas.setBorder(null);
        b_kelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kelasActionPerformed(evt);
            }
        });

        b_siswa.setBackground(new java.awt.Color(204, 102, 255));
        b_siswa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        b_siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Student Male.png"))); // NOI18N
        b_siswa.setText("Siswa");
        b_siswa.setBorder(null);
        b_siswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_siswaActionPerformed(evt);
            }
        });

        b_about.setBackground(new java.awt.Color(204, 102, 255));
        b_about.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        b_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/About2.png"))); // NOI18N
        b_about.setText("About");
        b_about.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b_about.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aboutActionPerformed(evt);
            }
        });

        b_logout.setBackground(new java.awt.Color(204, 102, 255));
        b_logout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        b_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Logout.png"))); // NOI18N
        b_logout.setText("Logout");
        b_logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b_logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBar_PanelLayout = new javax.swing.GroupLayout(sideBar_Panel);
        sideBar_Panel.setLayout(sideBar_PanelLayout);
        sideBar_PanelLayout.setHorizontalGroup(
            sideBar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBar_PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(sideBar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_jurusan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sideBar_PanelLayout.createSequentialGroup()
                        .addComponent(b_dasboard, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(b_guru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_kelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_siswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_about, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBar_PanelLayout.setVerticalGroup(
            sideBar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBar_PanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(b_dasboard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_guru, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_about, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content_Panel.setBackground(new java.awt.Color(255, 255, 255));
        content_Panel.setLayout(new java.awt.CardLayout());

        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Close.png"))); // NOI18N
        bClose.setBorder(null);
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_PanelLayout = new javax.swing.GroupLayout(main_Panel);
        main_Panel.setLayout(main_PanelLayout);
        main_PanelLayout.setHorizontalGroup(
            main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_PanelLayout.createSequentialGroup()
                .addComponent(sideBar_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_PanelLayout.createSequentialGroup()
                        .addGap(0, 1062, Short.MAX_VALUE)
                        .addComponent(bClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(content_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        main_PanelLayout.setVerticalGroup(
            main_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sideBar_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(main_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bClose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_dasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dasboardActionPerformed
        // TODO add your handling code here:
        content_Panel.removeAll();
        content_Panel.add(new panelDasboard());
        content_Panel.repaint();
        content_Panel.revalidate();
    }//GEN-LAST:event_b_dasboardActionPerformed

    private void b_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_jurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_jurusanActionPerformed

    private void b_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_guruActionPerformed

    private void b_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_kelasActionPerformed

    private void b_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_siswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_siswaActionPerformed

    private void b_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_aboutActionPerformed

    private void b_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_logoutActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_dasboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton b_about;
    private javax.swing.JButton b_dasboard;
    private javax.swing.JButton b_guru;
    private javax.swing.JButton b_jurusan;
    private javax.swing.JButton b_kelas;
    private javax.swing.JButton b_logout;
    private javax.swing.JButton b_siswa;
    private javax.swing.JPanel content_Panel;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JPanel sideBar_Panel;
    // End of variables declaration//GEN-END:variables
}
