/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202457201057;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class PanelGuru extends javax.swing.JPanel {

    /**
     * Creates new form PanelGuru
     */
    public PanelGuru() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Guru = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b_Close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t_NIP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_Nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_JenisKelamin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_guru = new javax.swing.JTable();
        b_Reset = new javax.swing.JButton();
        b_Hapus = new javax.swing.JButton();
        b_Ubah = new javax.swing.JButton();
        b_Tambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_Alamat = new javax.swing.JTextArea();

        panel_Guru.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 59));

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel1.setText("Data Guru");

        b_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Close.png"))); // NOI18N
        b_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_Close)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_Close)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("NIP");

        t_NIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_NIPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nama");

        t_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_NamaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        c_JenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jenis Kelamin--", "Laki-Laki", "Perempuan", " " }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Alamat");

        table_guru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama Guru", "Jenis Kelamin", "Alamat"
            }
        ));
        table_guru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_guruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_guru);

        b_Reset.setBackground(new java.awt.Color(51, 153, 255));
        b_Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Restart.png"))); // NOI18N
        b_Reset.setText("Reset");
        b_Reset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ResetActionPerformed(evt);
            }
        });

        b_Hapus.setBackground(new java.awt.Color(255, 51, 51));
        b_Hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Trash.png"))); // NOI18N
        b_Hapus.setText("Hapus");
        b_Hapus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_HapusActionPerformed(evt);
            }
        });

        b_Ubah.setBackground(new java.awt.Color(255, 153, 51));
        b_Ubah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_Ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Edit.png"))); // NOI18N
        b_Ubah.setText("Ubah");
        b_Ubah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_UbahActionPerformed(evt);
            }
        });

        b_Tambah.setBackground(new java.awt.Color(102, 255, 102));
        b_Tambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_Tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Plus.png"))); // NOI18N
        b_Tambah.setText("Tambah");
        b_Tambah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_TambahActionPerformed(evt);
            }
        });

        t_Alamat.setColumns(20);
        t_Alamat.setRows(5);
        jScrollPane2.setViewportView(t_Alamat);

        javax.swing.GroupLayout panel_GuruLayout = new javax.swing.GroupLayout(panel_Guru);
        panel_Guru.setLayout(panel_GuruLayout);
        panel_GuruLayout.setHorizontalGroup(
            panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_GuruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_GuruLayout.createSequentialGroup()
                        .addGroup(panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(t_NIP)
                            .addComponent(jLabel3)
                            .addComponent(t_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(c_JenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(panel_GuruLayout.createSequentialGroup()
                        .addGroup(panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_GuruLayout.createSequentialGroup()
                                .addComponent(b_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(b_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_GuruLayout.setVerticalGroup(
            panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_GuruLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_GuruLayout.createSequentialGroup()
                        .addComponent(t_NIP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_JenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_Ubah)
                    .addComponent(b_Tambah)
                    .addComponent(b_Hapus))
                .addGap(34, 34, 34)
                .addComponent(b_Reset)
                .addGap(0, 96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_NIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_NIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_NIPActionPerformed

    private void t_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_NamaActionPerformed

    private void b_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ResetActionPerformed
        // TODO add your handling code here:
        t_NIP.setText("");
        t_Nama.setText("");
        c_JenisKelamin.setSelectedIndex(0);
        t_Alamat.setText("");
    }//GEN-LAST:event_b_ResetActionPerformed

    private void b_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CloseActionPerformed
        // TODO add your handling code here:
        panel_Guru.setVisible(false);
    }//GEN-LAST:event_b_CloseActionPerformed

    private void table_guruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_guruMouseClicked
        // TODO add your handling code here:
        int baris = table_guru.getSelectedRow(); //ambil nilai baris
        
        //ambil nilai kolom
        String NIP = table_guru.getValueAt(baris, 0).toString();
        String nama = table_guru.getValueAt(baris, 1).toString();
        String gender = table_guru.getValueAt(baris, 2).toString();
        String alamat = table_guru.getValueAt(baris, 3).toString();
       
        //isi ke textField
        t_NIP.setText(NIP);
        t_Nama.setText(nama);
        c_JenisKelamin.setSelectedItem(gender);
        t_Alamat.setText(alamat);
    }//GEN-LAST:event_table_guruMouseClicked

    private void b_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_TambahActionPerformed
        // TODO add your handling code here: 
        String NIP = t_NIP.getText().trim();
        String nama = t_Nama.getText().trim();
        String gender = c_JenisKelamin.getSelectedItem().toString();
        String alamat = t_Alamat.getText().trim();
        
        if (!NIP.isEmpty()&&!nama.isEmpty() && !gender.isEmpty()&& !alamat.isEmpty()){
           DefaultTableModel model= (DefaultTableModel) table_guru.getModel();
           model.addRow(new Object[]{NIP,nama,gender,alamat});
           
           //Kosongkan textField setelah tambah
           t_NIP.setText("");
           t_Nama.setText("");
           c_JenisKelamin.setSelectedIndex(0);
           t_Alamat.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Lengkapi semua data terlebih dahulu!");
        }
        
    }//GEN-LAST:event_b_TambahActionPerformed

    private void b_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_UbahActionPerformed
        // TODO add your handling code here:
        int baris = table_guru.getSelectedRow();//ambil baris
        
        if (baris>=0){
            String NIP = t_NIP.getText().trim();
            String nama = t_Nama.getText().trim();
            String gender = c_JenisKelamin.getSelectedItem().toString();
            String alamat = t_Alamat.getText().trim();
            
            if (!NIP.isEmpty() && !nama.isEmpty() && !gender.isEmpty() && !alamat.isEmpty()) {
            //update isi tabel
            table_guru.setValueAt(NIP, baris, 0);
            table_guru.setValueAt(nama, baris, 1);
            table_guru.setValueAt(gender, baris, 2);
            table_guru.setValueAt(alamat, baris, 3);
            
            //kosongkan textField
            t_NIP.setText("");
            t_Nama.setText("");
            c_JenisKelamin.setSelectedIndex(0);
            t_Alamat.setText("");
            
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
        } else {
            JOptionPane.showMessageDialog(null, "Lengkapi data terlebih dahulu");
        }
        }else {
             JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
          }
    }//GEN-LAST:event_b_UbahActionPerformed

    private void b_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_HapusActionPerformed
        // TODO add your handling code here:
        int baris = table_guru.getSelectedRow(); // ambil baris yang dipilih

        if (baris >= 0) {
        int konfirmasi = JOptionPane.showConfirmDialog(
            null,
            "Apakah kamu yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) table_guru.getModel();
            model.removeRow(baris); // hapus baris dari model

            // Kosongkan TextField setelah hapus
            t_NIP.setText("");
            t_Nama.setText("");
            c_JenisKelamin.setSelectedIndex(0);
            t_Alamat.setText("");
        }

        } else {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!");
        }
        
    }//GEN-LAST:event_b_HapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Close;
    private javax.swing.JButton b_Hapus;
    private javax.swing.JButton b_Reset;
    private javax.swing.JButton b_Tambah;
    private javax.swing.JButton b_Ubah;
    private javax.swing.JComboBox<String> c_JenisKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_Guru;
    private javax.swing.JTextArea t_Alamat;
    private javax.swing.JTextField t_NIP;
    private javax.swing.JTextField t_Nama;
    private javax.swing.JTable table_guru;
    // End of variables declaration//GEN-END:variables
}
