/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni_202457201057;

import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author HP
 */
public class PanelSiswa extends javax.swing.JPanel {
    private String pathFoto = null;
    /**
     * Creates new form PanelSiswa
     */
    public PanelSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Siswa = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b_Close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_DataSiswa = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        t_NIS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_Nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c_JenisKelamin = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        t_TempatLahir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_TanggalLahir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_NoHp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        c_Kelas = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        b_tambah = new javax.swing.JButton();
        b_ubah = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        b_reset = new javax.swing.JButton();
        t_Foto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_Alamat = new javax.swing.JTextArea();
        b_Foto = new javax.swing.JButton();

        panel_Siswa.setBackground(new java.awt.Color(204, 204, 204));
        panel_Siswa.setPreferredSize(new java.awt.Dimension(1100, 735));

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel1.setText("Data Siswa");

        b_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Close.png"))); // NOI18N
        b_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_Close)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_Close)
                    .addComponent(jLabel1)))
        );

        table_DataSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Tempat Lahir", "Tanggal Lahir", "No. HP", "Kelas", "Alamat", "Foto"
            }
        ));
        table_DataSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_DataSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_DataSiswa);

        jLabel3.setText("NIS");

        jLabel4.setText("Nama");

        jLabel5.setText("Jenis Kelamin");

        c_JenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jenis Kelamin--", "Laki-laki", "Perempuan", " ", " " }));
        c_JenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_JenisKelaminActionPerformed(evt);
            }
        });

        jLabel6.setText("Tempat Lahir");

        jLabel7.setText("Tanggal Lahir");

        jLabel8.setText("No.Hp");

        jLabel9.setText("Kelas");

        c_Kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Kelas--", "A", "B", "C" }));

        jLabel10.setText("Alamat");

        b_tambah.setBackground(new java.awt.Color(102, 255, 102));
        b_tambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Plus.png"))); // NOI18N
        b_tambah.setText("Tambah");
        b_tambah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        b_ubah.setBackground(new java.awt.Color(255, 153, 51));
        b_ubah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Edit.png"))); // NOI18N
        b_ubah.setText("Ubah");
        b_ubah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ubahActionPerformed(evt);
            }
        });

        b_hapus.setBackground(new java.awt.Color(255, 51, 51));
        b_hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Trash.png"))); // NOI18N
        b_hapus.setText("Hapus");
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        b_reset.setBackground(new java.awt.Color(51, 153, 255));
        b_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Restart.png"))); // NOI18N
        b_reset.setText("Reset");
        b_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_resetActionPerformed(evt);
            }
        });

        t_Foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t_Foto.setText("Foto");
        t_Foto.setToolTipText("");
        t_Foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_Alamat.setColumns(20);
        t_Alamat.setRows(5);
        jScrollPane2.setViewportView(t_Alamat);

        b_Foto.setBackground(new java.awt.Color(204, 102, 255));
        b_Foto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202457201057/Gambar/Selfies.png"))); // NOI18N
        b_Foto.setText("Tambah Foto");
        b_Foto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        b_Foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_FotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_SiswaLayout = new javax.swing.GroupLayout(panel_Siswa);
        panel_Siswa.setLayout(panel_SiswaLayout);
        panel_SiswaLayout.setHorizontalGroup(
            panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_SiswaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_SiswaLayout.createSequentialGroup()
                        .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_SiswaLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(b_Foto)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(t_NIS)
                            .addComponent(jLabel4)
                            .addComponent(t_Nama)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(c_JenisKelamin, 0, 214, Short.MAX_VALUE)
                            .addComponent(t_TempatLahir)
                            .addComponent(t_TanggalLahir))
                        .addGap(100, 100, 100)
                        .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(t_NoHp)
                            .addComponent(c_Kelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_SiswaLayout.createSequentialGroup()
                        .addComponent(b_tambah)
                        .addGap(18, 18, 18)
                        .addComponent(b_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_hapus)
                        .addGap(18, 18, 18)
                        .addComponent(b_reset)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panel_SiswaLayout.setVerticalGroup(
            panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SiswaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_SiswaLayout.createSequentialGroup()
                        .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_NIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_NoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_SiswaLayout.createSequentialGroup()
                                .addComponent(c_JenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_TempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_TanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(panel_SiswaLayout.createSequentialGroup()
                        .addComponent(t_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_Foto)))
                .addGap(20, 20, 20)
                .addGroup(panel_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_tambah)
                    .addComponent(b_ubah)
                    .addComponent(b_hapus)
                    .addComponent(b_reset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void c_JenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_JenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_JenisKelaminActionPerformed

    private void b_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_resetActionPerformed
        // TODO add your handling code here:
        t_NIS.setText("");
        t_Nama.setText("");
        c_JenisKelamin.setSelectedIndex(0);
        t_TempatLahir.setText("");
        t_TanggalLahir.setText("");
        t_NoHp.setText("");
        c_Kelas.setSelectedIndex(0);
        t_Alamat.setText("");
        //reset foto
        t_Foto.setIcon(null);
        t_Foto.setText("Foto");
        pathFoto = null;
    }//GEN-LAST:event_b_resetActionPerformed

    private void b_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CloseActionPerformed
        // TODO add your handling code here:
        panel_Siswa.setVisible(false);
    }//GEN-LAST:event_b_CloseActionPerformed

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        // TODO add your handling code here:
        String nis = t_NIS.getText().trim();
        String nama = t_Nama.getText().trim();
        String gender = c_JenisKelamin.getSelectedItem().toString();
        String tmptlahir = t_TempatLahir.getText().trim();
        String tgllahir = t_TanggalLahir.getText().trim();
        String no_hp = t_NoHp.getText().trim();
        String kelas = c_Kelas.getSelectedItem().toString();
        String alamat = t_Alamat.getText().trim();
       
        if ((!nis.isEmpty()&&!nama.isEmpty() && !gender.isEmpty()&& !tmptlahir.isEmpty()) 
           && (!tgllahir.isEmpty() && !no_hp.isEmpty() && !kelas.isEmpty() && !alamat.isEmpty())){
           DefaultTableModel model= (DefaultTableModel) table_DataSiswa.getModel();
           model.addRow(new Object[]{nis,nama,gender,tmptlahir,tgllahir,no_hp,kelas,alamat,pathFoto});
           
           //Kosongkan textField setelah tambah
        t_NIS.setText("");
        t_Nama.setText("");
        c_JenisKelamin.setSelectedIndex(0);
        t_TempatLahir.setText("");
        t_TanggalLahir.setText("");
        t_NoHp.setText("");
        c_Kelas.setSelectedIndex(0);
        t_Alamat.setText("");
        t_Foto.setIcon(null);
        t_Foto.setText("Foto");
        pathFoto = null;
         
        } else {
            JOptionPane.showMessageDialog(null, "Lengkapi semua data terlebih dahulu!");
        }
    }//GEN-LAST:event_b_tambahActionPerformed

    private void table_DataSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_DataSiswaMouseClicked
        // TODO add your handling code here:
        int baris = table_DataSiswa.getSelectedRow(); //ambil nilai baris
        
        //ambil nilai kolom
        t_NIS.setText(table_DataSiswa.getValueAt(baris, 0).toString());
        t_Nama.setText(table_DataSiswa.getValueAt(baris, 1).toString());
        c_JenisKelamin.setSelectedItem(table_DataSiswa.getValueAt(baris, 2).toString());
        t_TempatLahir.setText(table_DataSiswa.getValueAt(baris, 3).toString());
        t_TanggalLahir.setText(table_DataSiswa.getValueAt(baris, 4).toString());
        t_NoHp.setText(table_DataSiswa.getValueAt(baris, 5).toString());
        c_Kelas.setSelectedItem(table_DataSiswa.getValueAt(baris, 6).toString());
        t_Alamat.setText(table_DataSiswa.getValueAt(baris, 7).toString());
        pathFoto = table_DataSiswa.getValueAt(baris, 8).toString(); 
    }//GEN-LAST:event_table_DataSiswaMouseClicked

    private void b_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ubahActionPerformed
        // TODO add your handling code here:
        int baris = table_DataSiswa.getSelectedRow();//ambil baris
        
        if (baris>=0){
        String nis = t_NIS.getText().trim();
        String nama = t_Nama.getText().trim();
        String gender = c_JenisKelamin.getSelectedItem().toString();
        String tmptlahir = t_TempatLahir.getText().trim();
        String tgllahir = t_TanggalLahir.getText().trim();
        String no_hp = t_NoHp.getText().trim();
        String kelas = c_Kelas.getSelectedItem().toString();
        String alamat = t_Alamat.getText().trim();
            
            if ((!nis.isEmpty()&&!nama.isEmpty() && !gender.isEmpty()&& !tmptlahir.isEmpty()) 
           && (!tgllahir.isEmpty() && !no_hp.isEmpty() && !kelas.isEmpty() && !alamat.isEmpty() && !pathFoto.isEmpty())) {
           
             // Ambil model dari tabel
        DefaultTableModel model = (DefaultTableModel) table_DataSiswa.getModel();

        // Update data di baris yang dipilih
        model.setValueAt(nis, baris, 0);
        model.setValueAt(nama, baris, 1);
        model.setValueAt(gender, baris, 2);
        model.setValueAt(tmptlahir, baris, 3);
        model.setValueAt(tgllahir, baris, 4);
        model.setValueAt(no_hp, baris, 5);
        model.setValueAt(kelas, baris, 6);
        model.setValueAt(alamat, baris, 7);
        model.setValueAt(pathFoto, baris, 8);
            
            //kosongkan textField
            t_NIS.setText("");
            t_Nama.setText("");
            c_JenisKelamin.setSelectedIndex(0);
            t_TempatLahir.setText("");
            t_TanggalLahir.setText("");
            t_NoHp.setText("");
            c_Kelas.setSelectedIndex(0);
            t_Alamat.setText("");
            t_Foto.setIcon(null);
            t_Foto.setText("Foto");
            pathFoto = null;
            
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
        } else {
            JOptionPane.showMessageDialog(null, "Lengkapi data terlebih dahulu");
        }
        }else {
             JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah");
          }
    }//GEN-LAST:event_b_ubahActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        // TODO add your handling code here:
        int baris = table_DataSiswa.getSelectedRow(); // ambil baris yang dipilih

        if (baris >= 0) {
        int konfirmasi = JOptionPane.showConfirmDialog(
            null,
            "Apakah kamu yakin ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) table_DataSiswa.getModel();
            model.removeRow(baris); // hapus baris dari model

            // Kosongkan TextField setelah hapus
             t_NIS.setText("");
            t_Nama.setText("");
            c_JenisKelamin.setSelectedIndex(0);
            t_TempatLahir.setText("");
            t_TanggalLahir.setText("");
            t_NoHp.setText("");
            c_Kelas.setSelectedIndex(0);
            t_Alamat.setText(" ");
            t_Foto.setIcon(null);
            t_Foto.setText("Foto");
            pathFoto = null;
        }

        } else {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!");
        }
    }//GEN-LAST:event_b_hapusActionPerformed

    private void b_FotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_FotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
    fc.setDialogTitle("Pilih Foto");
    fc.setFileFilter(new FileNameExtensionFilter("Gambar", "jpg", "jpeg", "png"));

    int hasil = fc.showOpenDialog(this);
    if (hasil == JFileChooser.APPROVE_OPTION) {
        File file = fc.getSelectedFile();
        pathFoto = file.getAbsolutePath(); // simpan path-nya

        ImageIcon icon = new ImageIcon(new ImageIcon(pathFoto).getImage().getScaledInstance(
                t_Foto.getWidth(), t_Foto.getHeight(), Image.SCALE_SMOOTH));
        t_Foto.setIcon(icon);
        t_Foto.setText(""); // hilangkan tulisan "Foto"
    }
    }//GEN-LAST:event_b_FotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Close;
    private javax.swing.JButton b_Foto;
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_reset;
    private javax.swing.JButton b_tambah;
    private javax.swing.JButton b_ubah;
    private javax.swing.JComboBox<String> c_JenisKelamin;
    private javax.swing.JComboBox<String> c_Kelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_Siswa;
    private javax.swing.JTextArea t_Alamat;
    private javax.swing.JLabel t_Foto;
    private javax.swing.JTextField t_NIS;
    private javax.swing.JTextField t_Nama;
    private javax.swing.JTextField t_NoHp;
    private javax.swing.JTextField t_TanggalLahir;
    private javax.swing.JTextField t_TempatLahir;
    private javax.swing.JTable table_DataSiswa;
    // End of variables declaration//GEN-END:variables
}
